### ISSUE TITLE
Background color not working

### ISSUE THREAD

**Issue by wonkeythemonkey** [Brackets-Themes/Solarized#1]
When I install this theme as an extension in Brackets 0.4.2 and activate it using the new, native "themes" interface, the background of my documents remain white. The text colors display correctly.

**Comment by MiguelCastillo** [comment]
@wonkeythemonkey Are you running any of the themes manager extensions?  E.g. Themes for Brackets or Themes?

**Comment by wonkeythemonkey** [comment]
I am running "Themes for Brackets." I used to use the old Themes extension before it was integrated, but I removed it. I installed this version of Solarized separately to make it easier to customize the extension manually.
