### ISSUE TITLE
"Visualize Tab" on by default

### ISSUE THREAD

**Issue by wonkeythemonkey** [Brackets-Themes/Solarized#2]
This theme displays an arrow ("➤") where lines are indented with tabs. This is a feature that some users may desire, but it is not shown in the demo screenshot for this theme. I believe that it should be disabled by default (can be done easily by commenting out line 92 in the main.less file), or else it should be visible in the screenshot.

**Comment by MiguelCastillo** [comment]
@wonkeythemonkey I use white spaces, that's why the screenshot does not show the crazy arrows.  Are you thinking that I update the screenshot?  Or maybe add a note in the description to explain the crazy arrow?

**Comment by wonkeythemonkey** [comment]
My personal preference is to turn off the arrows in the theme. They are turned off in the default Brackets themes, and I found it confusing when they started showing up in this one.

It's too bad that there are no settings for themes aside from manually editing the CSS files. I'd love to be able to turn a feature like this on or off, or toggle between dark and light versions of the same theme when available.
